server:
  port: 8080

logging:
  level:
    root: info
    com.github.mapper: trace

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.github.mapper

spring:
  datasource:
    platform: H2
#    schema: classpath:h2/H2_TYPE.sql
#    data: classpath:h2/init.sql
    username: sa
    password: 111111
    url: jdbc:h2:/Users/alex/Documents/h2/customQuery;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092;USER=sa;PASSWORD=111111
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 2
      initial-size: 5
      max-active: 10
#      filters:
#      filter:
#        wall:
#          enabled: true
#          db-type: h2
#          config:
#            delete-allow: false
#            drop-table-allow: false
#        stat:
#          enabled: true
#          db-type: h2
#          log-slow-sql: true
#        slf4j:
#          enabled: true
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: true
#        #设置监控页面的登录名和密码
#        login-username: admin
#        login-password: 111111


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent-output: true


datasource1:
  platform: H2
  #    schema: classpath:h2/H2_TYPE.sql
  #    data: classpath:h2/init.sql
  username: sa
  password: 111111
  url: jdbc:h2:/Users/alex/Documents/h2/customQuery_1;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9093;USER=sa;PASSWORD=111111
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    min-idle: 2
    initial-size: 5
    max-active: 10
